name: Profile Download Tracker
on:
  schedule:
    - cron: '0 0 * * *'  # Daily updates
  workflow_dispatch:

jobs:
  update-downloads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate Total Downloads
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          total=0
          repos=$(gh api users/atulhacks/repos --paginate --jq '.[].name')
          
          while read -r repo; do
            releases=$(gh api repos/atulhacks/$repo/releases --paginate)
            downloads=$(echo "$releases" | jq -r '.[].assets[].download_count' | awk '{sum+=$1} END {print sum}')
            total=$((total + downloads))
          done <<< "$repos"

          echo '{"schemaVersion":1,"label":"Downloads","message":"'$total'","color":"success"}' > total.json

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add total.json
          git commit -m "📈 Update download count"
          git push
