name: Profile Download Tracker
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-downloads:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write permissions
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # Keep the authentication token available

      - name: Calculate Total Downloads
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          total=0
          repos=$(gh api users/atulhacks/repos --paginate --jq '.[].name')
          
          while read -r repo; do
            releases=$(gh api repos/atulhacks/$repo/releases --paginate)
            downloads=$(echo "$releases" | jq -r '.[].assets[].download_count' | awk '{sum+=$1} END {print sum}')
            total=$((total + downloads))
          done <<< "$repos"

          echo '{"schemaVersion":1,"label":"Downloads","message":"'$total'","color":"success"}' > total.json

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: '📈 Update download count'
          add: 'total.json'
          push: true
