name: Profile Download Tracker
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-downloads:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Setup GitHub CLI
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Calculate Total Downloads
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get all repository names (handles pagination)
          repos=$(gh api users/atulhacks/repos --paginate --jq '.[].name' | tr '\n' ' ')
          
          total=0
          for repo in $repos; do
            echo "Processing $repo..."
            
            # Get releases with assets
            releases=$(gh api repos/atulhacks/$repo/releases --paginate)
            
            # Sum download counts
            downloads=$(echo "$releases" | \
              jq -r '.[].assets[].download_count' | \
              awk '{sum+=$1} END {print sum+0}')
            
            total=$((total + downloads))
          done

          # Generate badge JSON
          echo "Total downloads: $total"
          jq -n \
            --arg total "$total" \
            --arg color $(if [ $total -ge 1000 ]; then echo "success"; elif [ $total -ge 500 ]; then echo "yellow"; else echo "critical"; fi) \
            '{schemaVersion:1, label:"Downloads", message:$total, color:$color}' > total.json

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "📈 Update download count (${{ steps.calculate.outputs.total }})"
          add: "total.json"
          pull: true
          push: true
          force: true
